import { createFileRoute } from "@tanstack/react-router";
import { ArrowUpRight, BookOpen, Code2, Download, FileText, Github, Linkedin, Mail, Send, ShieldCheck } from "lucide-react";
import { useState } from "react";

const githubUrl = "https://github.com/thatianeormindo";
const linkedinUrl = "https://www.linkedin.com/in/thatianemalheiros/?skipRedirect=true";
const projects = [
  { title: "API Security Lab", status: "Em desenvolvimento", objective: "Laboratório local sobre autenticação, autorização, controle de acesso, exposição de dados e lógica de negócio.", technologies: ["Python", "FastAPI", "PostgreSQL", "Docker"], tasks: [] },
  { title: "Security Headers Analyzer", status: "Planejado", objective: "Ferramenta para analisar headers de segurança em aplicações próprias ou autorizadas.", technologies: ["Python", "CLI", "JSON"], tasks: [] },
  { title: "Vulnerability Assessment Report", status: "Planejado", objective: "Modelo de relatório com escopo, metodologia, evidências, severidade, impacto, recomendações e reteste.", technologies: ["Markdown", "PDF", "Template"], tasks: [] },
  { title: "Portfólio pessoal de AppSec", status: "Em desenvolvimento", objective: "Site responsivo para apresentar estudos, projetos práticos, competências e formas de colaboração em segurança de aplicações.", technologies: ["React", "TypeScript", "Vite", "TanStack Router", "Tailwind CSS"], tasks: ["npm install", "npm run dev", "npm run build", "VS Code: Run Task / Iniciar portfólio"] },
];
const competencies = ["Application Security", "Web Application Security", "API Security", "Vulnerability Assessment", "OWASP", "Autenticação", "Autorização", "Lógica de negócio", "HTTP/HTTPS", "REST APIs", "Security Testing", "Ethical Hacking em ambientes autorizados", "Debian/Linux", "Python", "Bash", "Git", "GitHub", "Docker", "Security Automation", "Automação com IA"];
const studies = ["OWASP", "OWASP API Security Top 10", "PortSwigger Web Security Academy", "Laboratórios controlados de segurança web", "Projetos próprios em AppSec"];

function Heading({ eyebrow, title, children }: { eyebrow: string; title: string; children?: React.ReactNode }) {
  return <div className="mb-10 max-w-2xl"><p className="mb-3 font-mono text-xs uppercase tracking-[0.18em] text-red-500">{eyebrow}</p><h2 className="text-3xl font-semibold tracking-tight text-white sm:text-4xl">{title}</h2>{children && <p className="mt-4 leading-relaxed text-zinc-400">{children}</p>}</div>;
}

export const Route = createFileRoute("/")({
  head: () => ({ meta: [{ title: "Thatiane Malheiros | AppSec" }, { name: "description", content: "Portfólio de Thatiane Malheiros: AppSec, segurança web e APIs, vulnerability assessment e automação com IA." }] }),
  component: Portfolio,
});

function Portfolio() {
  const [formStatus, setFormStatus] = useState<"idle" | "success" | "error">("idle");
  const [formData, setFormData] = useState({ name: "", email: "", message: "" });
  function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const valid = formData.name.trim() && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.email) && formData.message.trim();
    if (!valid) { setFormStatus("error"); return; }
    setFormStatus("success");
    setFormData({ name: "", email: "", message: "" });
  }
  const approach = ["Investigo comportamento técnico e lógica de negócio.", "Valido descobertas manualmente em ambientes autorizados.", "Documento riscos, impacto, correções e limitações."];
  return <main className="min-h-screen bg-black text-zinc-100 antialiased">
    <nav className="sticky top-0 z-20 border-b border-zinc-800/80 bg-black/90 backdrop-blur-md"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 sm:px-8"><a href="#sobre" className="font-mono text-sm font-semibold text-white">TM<span className="text-red-500">.</span></a><div className="hidden gap-6 font-mono text-xs text-zinc-400 sm:flex"><a href="#projetos" className="hover:text-white">Projetos</a><a href="#writeups" className="hover:text-white">Write-ups</a><a href="#competencias" className="hover:text-white">Competências</a><a href="#contato" className="hover:text-white">Contato</a></div><a href="mailto:thatiane@proton.me" aria-label="Enviar e-mail" className="text-zinc-400 hover:text-red-500"><Mail className="size-4" /></a></div></nav>
    <section id="sobre" className="border-b border-zinc-800/80 px-5 py-20 sm:px-8 sm:py-32"><div className="mx-auto max-w-6xl"><div className="max-w-4xl"><div className="mb-8 inline-flex items-center gap-2 border border-zinc-800 bg-zinc-950 px-3 py-2 font-mono text-xs text-zinc-400"><ShieldCheck className="size-4 text-red-500" /> Profissional em desenvolvimento</div><h1 className="text-5xl font-semibold tracking-tight text-white sm:text-7xl">Thatiane Malheiros</h1><p className="mt-6 text-lg leading-relaxed text-zinc-300 sm:text-xl">AppSec <span className="text-red-500">|</span> Segurança Web e APIs <span className="text-red-500">|</span> Vulnerability Assessment <span className="text-red-500">|</span> Automação com IA</p><p className="mt-8 max-w-3xl text-base leading-8 text-zinc-400">Investigo como aplicações, APIs e fluxos de negócio podem falhar, especialmente em autenticação, permissões e lógica de negócio. Desenvolvo estudos e projetos práticos em ambientes controlados e autorizados, utilizando Debian/Linux, Python, Bash, Git e automação com IA como ferramentas de análise e aprendizado.</p><p className="mt-5 max-w-2xl text-sm leading-7 text-zinc-500">Tenho interesse em projetos open source, colaboração assíncrona e oportunidades remotas em equipes distribuídas.</p><div className="mt-10 flex flex-wrap gap-3"><a href="#projetos" className="inline-flex items-center gap-2 bg-red-600 px-5 py-3 font-mono text-sm font-semibold text-white hover:bg-red-500">Ver projetos <ArrowUpRight className="size-4" /></a><a href={githubUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 border border-zinc-700 px-5 py-3 font-mono text-sm text-zinc-300 hover:border-zinc-500 hover:text-white">Ver projetos no GitHub <Github className="size-4" /></a><a href="mailto:thatiane@proton.me" className="inline-flex items-center gap-2 border border-zinc-700 px-5 py-3 font-mono text-sm text-zinc-300 hover:border-red-500 hover:text-white">Entrar em contato <Mail className="size-4" /></a></div></div></div></section>
    <section className="border-b border-zinc-800/80 px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-6xl"><Heading eyebrow="02 / método" title="Como trabalho">Uma abordagem prática, responsável e orientada por evidências.</Heading><div className="grid gap-px border border-zinc-800 bg-zinc-800 md:grid-cols-3">{approach.map((item, index) => <div key={item} className="bg-black p-7"><span className="font-mono text-sm text-red-500">0{index + 1}</span><Code2 className="mt-8 size-5 text-zinc-500" /><p className="mt-5 leading-7 text-zinc-300">{item}</p></div>)}</div></div></section>
    <section id="projetos" className="border-b border-zinc-800/80 px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-6xl"><Heading eyebrow="03 / prática" title="Projetos práticos">Estudos e laboratórios desenvolvidos em ambientes controlados e autorizados.</Heading><div className="grid gap-5 lg:grid-cols-3">{projects.map((project, index) => <article key={project.title} className="flex flex-col border border-zinc-800 bg-zinc-950 p-6 hover:border-zinc-600"><div className="flex items-start justify-between gap-4"><span className="font-mono text-xs text-zinc-600">0{index + 1}</span><span className={`border px-2 py-1 font-mono text-[10px] ${project.status === "Em desenvolvimento" ? "border-red-900/80 text-red-400" : "border-zinc-700 text-zinc-500"}`}>{project.status}</span></div><h3 className="mt-8 text-xl font-semibold text-white">{project.title}</h3><p className="mt-4 flex-1 text-sm leading-7 text-zinc-400"><span className="font-mono text-xs uppercase text-zinc-600">Objetivo</span><br />{project.objective}</p><div className="mt-6 flex flex-wrap gap-2">{project.technologies.map((technology) => <span key={technology} className="bg-zinc-900 px-2 py-1 font-mono text-[11px] text-zinc-400">{technology}</span>)}</div>{project.tasks.length > 0 && <div className="mt-6 border-t border-zinc-800 pt-5"><p className="font-mono text-[10px] uppercase text-zinc-600">Tasks utilizadas</p><ul className="mt-2 space-y-1 text-xs text-zinc-400">{project.tasks.map((task) => <li key={task}>$ {task}</li>)}</ul></div>}<div className="mt-7 flex gap-4 border-t border-zinc-800 pt-5"><a href={githubUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 font-mono text-xs text-zinc-400 hover:text-white"><Github className="size-3.5" /> GitHub</a><span className="inline-flex items-center gap-2 font-mono text-xs text-zinc-600"><FileText className="size-3.5" /> Write-up em breve</span></div></article>)}</div></div></section>
    <section id="writeups" className="border-b border-zinc-800/80 px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-6xl"><Heading eyebrow="04 / documentação" title="Write-ups">Write-ups em construção. Em breve, análises técnicas de laboratórios autorizados, projetos próprios e aprendizados em AppSec.</Heading><div className="border-l-2 border-red-600 bg-zinc-950 p-6 font-mono text-sm text-zinc-400">status: em construção<br />escopo: laboratórios autorizados + projetos próprios</div></div></section>
    <section id="competencias" className="border-b border-zinc-800/80 px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-6xl"><Heading eyebrow="05 / repertório" title="Competências">Conhecimentos técnicos e práticos em desenvolvimento contínuo.</Heading><div className="flex flex-wrap gap-2">{competencies.map((skill) => <span key={skill} className="border border-zinc-800 bg-zinc-950 px-3 py-2 text-sm text-zinc-300">{skill}</span>)}</div></div></section>
    <section className="border-b border-zinc-800/80 px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-6xl"><Heading eyebrow="06 / aprendizado" title="Estudos e laboratórios">Recursos e plataformas utilizados no desenvolvimento de conhecimento em AppSec.</Heading><div className="grid gap-3 sm:grid-cols-2">{studies.map((study) => <div key={study} className="flex items-center gap-3 border border-zinc-800 bg-zinc-950 p-4 text-sm text-zinc-300"><BookOpen className="size-4 shrink-0 text-red-500" />{study}</div>)}</div></div></section>
    <section className="border-b border-zinc-800/80 px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-6xl"><Heading eyebrow="07 / colaboração" title="Open source e trabalho remoto">Tenho interesse em contribuir com projetos open source relacionados a segurança, desenvolvimento e automação. Busco oportunidades remotas em ambientes colaborativos, com comunicação clara, documentação técnica e colaboração assíncrona.</Heading><a href={githubUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 font-mono text-sm text-red-400 hover:text-red-300">Conhecer GitHub <ArrowUpRight className="size-4" /></a></div></section>
    <section className="border-b border-zinc-800/80 px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-6xl"><Heading eyebrow="08 / documento" title="Currículo">O currículo em PDF será disponibilizado quando estiver pronto.</Heading><button type="button" disabled className="inline-flex cursor-not-allowed items-center gap-2 border border-zinc-800 px-5 py-3 font-mono text-sm text-zinc-600"><Download className="size-4" /> Currículo em atualização</button></div></section>
    <section id="contato" className="px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-6xl"><Heading eyebrow="09 / contato" title="Vamos conversar">Para oportunidades, colaboração ou discussões sobre segurança de aplicações.</Heading><div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr]"><div className="space-y-5"><a href="mailto:thatiane@proton.me" className="flex items-center gap-3 text-zinc-300 hover:text-red-400"><Mail className="size-4 text-red-500" /> thatiane@proton.me</a><a href={githubUrl} target="_blank" rel="noreferrer" className="flex items-center gap-3 text-zinc-300 hover:text-red-400"><Github className="size-4 text-red-500" /> github.com/thatianeormindo</a><a href={linkedinUrl} target="_blank" rel="noreferrer" className="flex items-center gap-3 text-zinc-300 hover:text-red-400"><Linkedin className="size-4 text-red-500" /> linkedin.com/in/thatianemalheiros</a></div><form onSubmit={submit} className="space-y-5" noValidate><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm text-zinc-400">Nome<input required value={formData.name} onChange={(event) => setFormData({ ...formData, name: event.target.value })} className="mt-2 w-full border border-zinc-800 bg-zinc-950 px-4 py-3 text-white outline-none focus:border-red-600" /></label><label className="text-sm text-zinc-400">E-mail<input required type="email" value={formData.email} onChange={(event) => setFormData({ ...formData, email: event.target.value })} className="mt-2 w-full border border-zinc-800 bg-zinc-950 px-4 py-3 text-white outline-none focus:border-red-600" /></label></div><label className="block text-sm text-zinc-400">Mensagem<textarea required rows={5} value={formData.message} onChange={(event) => setFormData({ ...formData, message: event.target.value })} className="mt-2 w-full resize-y border border-zinc-800 bg-zinc-950 px-4 py-3 text-white outline-none focus:border-red-600" /></label>{formStatus === "success" && <p role="status" className="border border-emerald-900 bg-emerald-950/30 p-3 text-sm text-emerald-400">Mensagem validada com sucesso. Para enviar, use o e-mail ao lado.</p>}{formStatus === "error" && <p role="alert" className="border border-red-900 bg-red-950/30 p-3 text-sm text-red-400">Preencha nome, e-mail válido e mensagem.</p>}<button type="submit" className="inline-flex items-center gap-2 bg-red-600 px-5 py-3 font-mono text-sm font-semibold text-white hover:bg-red-500"><Send className="size-4" /> Validar mensagem</button></form></div></div></section>
    <footer className="border-t border-zinc-800 px-5 py-8 sm:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between font-mono text-xs text-zinc-600"><span>Thatiane Malheiros</span><span>AppSec / 2026</span></div></footer>
  </main>;
}