/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Index_oldRouteImport } from './routes/index_old'
import { Route as Index_old2RouteImport } from './routes/index_old2'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Index_oldRoute = Index_oldRouteImport.update({
  id: '/index_old',
  path: '/index_old',
  getParentRoute: () => rootRouteImport,
} as any)
const Index_old2Route = Index_old2RouteImport.update({
  id: '/index_old2',
  path: '/index_old2',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/index_old': typeof Index_oldRoute
  '/index_old2': typeof Index_old2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/index_old': typeof Index_oldRoute
  '/index_old2': typeof Index_old2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/index_old': typeof Index_oldRoute
  '/index_old2': typeof Index_old2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/index_old' | '/index_old2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/index_old' | '/index_old2'
  id: '__root__' | '/' | '/index_old' | '/index_old2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Index_oldRoute: typeof Index_oldRoute
  Index_old2Route: typeof Index_old2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index_old': {
      id: '/index_old'
      path: '/index_old'
      fullPath: '/index_old'
      preLoaderRoute: typeof Index_oldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index_old2': {
      id: '/index_old2'
      path: '/index_old2'
      fullPath: '/index_old2'
      preLoaderRoute: typeof Index_old2RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Index_oldRoute: Index_oldRoute,
  Index_old2Route: Index_old2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
